spring:
  application:
    name: service-provider-admin
  zipkin:
    base-url: http://192.168.179.144:9411

server:
  port: 11000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/